FROM python:3.13-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/wiktextract
COPY . .
RUN pip install --no-cache-dir .

ENTRYPOINT ["wiktwords"]
